SET FOREIGN_KEY_CHECKS=0;

DELETE R FROM TM_USER_PROJECT_ROLE R INNER JOIN TM_USER_PROFILE P ON R.USER_PROFILE_ID = P.USER_PROFILE_ID WHERE P.USERNAME='OPE_user';

DELETE L FROM TM_PROJECT_USER_LANGUAGE L INNER JOIN TM_USER_PROFILE P ON L.USER_PROFILE_ID = P.USER_PROFILE_ID WHERE P.USERNAME='OPE_user';

DELETE FROM TM_USER_PROFILE WHERE USERNAME='OPE_user';

SET FOREIGN_KEY_CHECKS=1;
