SET FOREIGN_KEY_CHECKS = 0;
ALTER TABLE `TM_TERMENTRY_RESOURCE_TRACK` MODIFY COLUMN `TERMENTRY_ID` varchar(40) NULL DEFAULT NULL AFTER `RESOURCE_NAME`;
ALTER TABLE `TM_TERMENTRY_RESOURCE_TRACK` DROP COLUMN `ID`;
SET FOREIGN_KEY_CHECKS = 1;