package org.gs4tr.termmanager.service.file.analysis.model;

public enum AlertSubject {
    ATTRIBUTE_CHECK, FILE_NOT_FOUND, FILE_PARSE_ERROR, HEADER_CHECK, HIDDEN_COLUMN, HIDDEN_ROW, HIDDEN_WORKSHEET, INVALID_FILE_FORMAT, MULTIPLE_WORKSHEETS, NO_COMMON_SOURCE_LANGUAGE, STATUS_CHECK;
}
