SET FOREIGN_KEY_CHECKS = 0;

INSERT INTO TM_USER_ROLE SELECT TM_USER_PROFILE.USER_PROFILE_ID, TM_ROLE.ROLE_ID FROM TM_USER_PROFILE INNER JOIN TM_ROLE ON TM_ROLE.GENERIC=TM_USER_PROFILE.GENERIC AND TM_ROLE.ROLE_TYPE='1' AND TM_ROLE.GENERIC='1';
DROP TABLE IF EXISTS TM_USER_LANGUAGE;

INSERT IGNORE INTO TM_POLICY (POLICY_ID, CATEGORY, POLICY_TYPE) VALUES ('POLICY_TM_TERM_DEMOTE_TO_ON_HOLD_TERM_STATUS', 'Task',	0);
INSERT IGNORE INTO TM_POLICY (POLICY_ID, CATEGORY, POLICY_TYPE) VALUES ('POLICY_TM_TERM_DEMOTE_TO_PENDING_APPROVAL_TERM_STATUS', 'Task',	0);

INSERT IGNORE INTO TM_POLICY (POLICY_ID, CATEGORY, POLICY_TYPE) VALUES ('POLICY_TM_USER_SEND_CONNECTION', 'Task',	0);

INSERT IGNORE INTO TM_ROLE_POLICY (ROLE_ID, POLICY_ID) SELECT ROLE_ID, 'POLICY_TM_USER_SEND_CONNECTION' FROM TM_ROLE_POLICY WHERE ROLE_ID IN ('super_user', 'power_user');

CREATE TABLE `TM_POWER_USER_PROJECT_ROLE` ( `POWER_USER_PROJECT_ROLE_ID` bigint(20) NOT NULL AUTO_INCREMENT,`ROLE_ID` varchar(50) COLLATE utf8_unicode_ci NOT NULL,`USER_PROFILE_ID` bigint(20) NOT NULL, PRIMARY KEY (`POWER_USER_PROJECT_ROLE_ID`),  UNIQUE KEY `UK_anam9ky4uu4wjo34nm2458m` (`USER_PROFILE_ID`), KEY `FK_p1kgc5grdd6odb1k2c5uc2noa` (`ROLE_ID`), CONSTRAINT `FK_anam9ky4uu4wjo34nm2458m` FOREIGN KEY (`USER_PROFILE_ID`) REFERENCES `TM_USER_PROFILE` (`USER_PROFILE_ID`), CONSTRAINT `FK_p1kgc5grdd6odb1k2c5uc2noa` FOREIGN KEY (`ROLE_ID`) REFERENCES `TM_ROLE` (`ROLE_ID`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT IGNORE INTO TM_POWER_USER_PROJECT_ROLE(ROLE_ID,USER_PROFILE_ID) SELECT 'power_user' AS ROLE_ID,u.USER_PROFILE_ID AS USER_PROFILE_ID FROM TM_USER_PROFILE AS u WHERE u.USER_TYPE=2;

SET FOREIGN_KEY_CHECKS = 1;