SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM TM_TERMENTRY_DESCRIPTION WHERE TM_TERMENTRY_DESCRIPTION.TERMENTRY_ID IN (SELECT TM_TERMENTRY.TERMENTRY_ID FROM TM_TERMENTRY);

DELETE FROM TM_TERM_HISTORY WHERE TM_TERM_HISTORY.TERMENTRY_HISTORY_ID IN (SELECT TM_TERMENTRY_HISTORY.TERMENTRY_HISTORY_ID FROM TM_TERMENTRY_HISTORY INNER JOIN TM_TERMENTRY ON TM_TERMENTRY.TERMENTRY_ID = TM_TERMENTRY_HISTORY.TERMENTRY_ID);

DELETE FROM TM_TERMENTRY_HISTORY WHERE TM_TERMENTRY_HISTORY.TERMENTRY_ID IN (SELECT TM_TERMENTRY.TERMENTRY_ID FROM TM_TERMENTRY);

DELETE FROM TM_TERM_DESCRIPTION WHERE TM_TERM_DESCRIPTION.TERM_ID IN (SELECT TM_TERM.TERM_ID FROM TM_TERM INNER JOIN TM_TERMENTRY ON TM_TERMENTRY.TERMENTRY_ID = TM_TERM.TERMENTRY_ID);

DELETE FROM TM_TERM WHERE TM_TERM.TERMENTRY_ID IN (SELECT TM_TERMENTRY.TERMENTRY_ID FROM TM_TERMENTRY);

DELETE FROM TM_TERMENTRY;

UPDATE TM_PROJECT_DETAIL SET TM_PROJECT_DETAIL.TERMENTRY_COUNT = 0, TM_PROJECT_DETAIL.TERM_COUNT = 0, TM_PROJECT_DETAIL.APPROVE_TERM_COUNT = 0, TM_PROJECT_DETAIL.FORBIDDEN_TERM_COUNT = 0;

UPDATE TM_PROJECT_LANGUAGE_DETAIL SET TM_PROJECT_LANGUAGE_DETAIL.APPROVE_TERM_COUNT = 0, TM_PROJECT_LANGUAGE_DETAIL.FORBIDDEN_TERM_COUNT = 0, TM_PROJECT_LANGUAGE_DETAIL.TERMENTRY_COUNT = 0, TM_PROJECT_LANGUAGE_DETAIL.TERM_COUNT = 0;

SET FOREIGN_KEY_CHECKS = 1;