SET FOREIGN_KEY_CHECKS = 0;

UPDATE TM_USER_LANGUAGE SET LANGUAGE_ID = 'ru-UA' WHERE LANGUAGE_ID = 'ru-UK';
UPDATE TM_PROJECT_LANGUAGE SET LANGUAGE_ID = 'ru-UA' WHERE LANGUAGE_ID = 'ru-UK';
UPDATE TM_PROJECT_USER_LANGUAGE SET LANGUAGE_ID = 'ru-UA' WHERE LANGUAGE_ID = 'ru-UK';
UPDATE TM_PROJECT_LANGUAGE_DETAIL SET LANGUAGE_ID = 'ru-UA' WHERE LANGUAGE_ID = 'ru-UK';
UPDATE TM_SUBMISSION_LANGUAGE SET LANGUAGE_ID = 'ru-UA' WHERE LANGUAGE_ID = 'ru-UK';

ALTER TABLE `TM_TERMENTRY_AUDIT_METADATA` DROP FOREIGN KEY `FK7B194C32B368A8BE`;
ALTER TABLE `TM_TERMENTRY_AUDIT_METADATA` DROP INDEX `FK7B194C32B368A8BE`;

ALTER TABLE `TM_TERM_DESCRIPTION` DROP FOREIGN KEY `FKD1BBE98FB368A8BE`;
ALTER TABLE `TM_TERM_DESCRIPTION` DROP INDEX `FKD1BBE98FB368A8BE`;

ALTER TABLE `TM_TERM` DROP FOREIGN KEY `FKE4528E72BD8BDFD6`;
ALTER TABLE `TM_TERM` DROP INDEX `FKE4528E72BD8BDFD6`;

ALTER TABLE `TM_DELETED_TERM` DROP FOREIGN KEY `FK68C3B8F8BD8BDFD6`;
ALTER TABLE `TM_DELETED_TERM` DROP INDEX `FK68C3B8F8BD8BDFD6`;

ALTER TABLE `TM_TERMENTRY_DESCRIPTION` DROP FOREIGN KEY `FKAB987F3DBD8BDFD6`;
ALTER TABLE `TM_TERMENTRY_DESCRIPTION` DROP INDEX `FKAB987F3DBD8BDFD6`;

ALTER TABLE `TM_TERMENTRY` DROP FOREIGN KEY `FK158FB920E3A5C25D`;
ALTER TABLE `TM_TERMENTRY` DROP INDEX `FK158FB920E3A5C25D`;

ALTER TABLE `TM_SUBMISSION_TERM_COMMENT` DROP FOREIGN KEY `FKDF8423B92145337`;
ALTER TABLE `TM_SUBMISSION_TERM_COMMENT` DROP INDEX `FKDF8423B92145337`;

ALTER TABLE `TM_SUBMISSION_TERM_DESCRIPTION` DROP FOREIGN KEY `FK90D674562145337`;
ALTER TABLE `TM_SUBMISSION_TERM_DESCRIPTION` DROP INDEX `FK90D674562145337`;

ALTER TABLE `TM_TRANSLATION_HISTORY` DROP FOREIGN KEY `FKC4071E002145337`;
ALTER TABLE `TM_TRANSLATION_HISTORY` DROP INDEX `FKC4071E002145337`;

ALTER TABLE `TM_SUBMISSION_TERM` DROP FOREIGN KEY `FK9F09CBB9B368A8BE`;
ALTER TABLE `TM_SUBMISSION_TERM` DROP INDEX `FK9F09CBB9B368A8BE`;
ALTER TABLE `TM_SUBMISSION_TERM` DROP FOREIGN KEY `FK9F09CBB998FE1537`;
ALTER TABLE `TM_SUBMISSION_TERM` DROP INDEX `FK9F09CBB998FE1537`;

ALTER TABLE `TM_TERMENTRY_RESOURCE_TRACK` DROP FOREIGN KEY `FKF5439EB9BD8BDFD6`;
ALTER TABLE `TM_TERMENTRY_RESOURCE_TRACK` DROP INDEX `FKF5439EB9BD8BDFD6`;

ALTER TABLE `TM_USER_DASHBOARD_PROJECT` DROP FOREIGN KEY `FK403714035FBAD86`;
ALTER TABLE `TM_USER_DASHBOARD_PROJECT` DROP INDEX `FK403714035FBAD86`;

ALTER TABLE `TM_USER_PROFILE` MODIFY COLUMN `TARGET_LANGUAGE` longtext NULL AFTER `SOURCE_LANGUAGE`;

DELETE FROM TM_USER_PROFILE_METADATA;

DROP TABLE `TM_TERMENTRY_AUDIT_METADATA`;
DROP TABLE `TM_TERM_DESCRIPTION`;
DROP TABLE `TM_TERM`;
DROP TABLE `TM_DELETED_TERM`;
DROP TABLE `TM_TERMENTRY_DESCRIPTION`;
DROP TABLE `TM_SUBMISSION_TERM_COMMENT`;
DROP TABLE `TM_SUBMISSION_TERM_DESCRIPTION`;
DROP TABLE `TM_TRANSLATION_HISTORY`;
DROP TABLE `TM_SUBMISSION_TERM`;
DROP TABLE `TM_TERMENTRY`;

SET FOREIGN_KEY_CHECKS = 1;