SET FOREIGN_KEY_CHECKS = 0;
UPDATE TM_INDEX_BACKUP_ENTRY SET CORE_NAME = 'regular' WHERE CORE_NAME = 'REGULAR_TERMS';
UPDATE TM_INDEX_BACKUP_ENTRY SET CORE_NAME = 'submission' WHERE CORE_NAME = 'SUBMISSION_TERMS';
DELETE st FROM TM_STATISTICS st WHERE st.PROJECT_USER_LANGUAGE_ID IN (SELECT pul2.PROJECT_USER_LANGUAGE_ID FROM TM_PROJECT_USER_LANGUAGE pul1, TM_PROJECT_USER_LANGUAGE pul2 WHERE pul1.PROJECT_USER_LANGUAGE_ID > pul2.PROJECT_USER_LANGUAGE_ID AND pul1.PROJECT_ID = pul2.PROJECT_ID AND pul1.USER_PROFILE_ID = pul2.USER_PROFILE_ID AND pul1.LANGUAGE_ID = pul2.LANGUAGE_ID);
DELETE pul2 FROM TM_PROJECT_USER_LANGUAGE pul1, TM_PROJECT_USER_LANGUAGE pul2 WHERE pul1.PROJECT_USER_LANGUAGE_ID > pul2.PROJECT_USER_LANGUAGE_ID AND pul1.PROJECT_ID = pul2.PROJECT_ID AND pul1.USER_PROFILE_ID = pul2.USER_PROFILE_ID AND pul1.LANGUAGE_ID = pul2.LANGUAGE_ID;
ALTER IGNORE TABLE TM_PROJECT_USER_LANGUAGE ADD UNIQUE INDEX IDX_PRO_USR_LANG_UNIQUE (PROJECT_ID, USER_PROFILE_ID, LANGUAGE_ID) USING BTREE;
ALTER IGNORE TABLE TM_USER_PROJECT_ROLE ADD UNIQUE INDEX IDX_USR_PRO_ROLE_UNIQUE (USER_PROFILE_ID, PROJECT_ID, ROLE_ID) USING BTREE;
SET FOREIGN_KEY_CHECKS = 1;