SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE `TM_PROJECT` ADD COLUMN `AVAILABLE_DESCRIPTION` BIT DEFAULT 0;

INSERT IGNORE INTO TM_POLICY (POLICY_ID, CATEGORY, POLICY_TYPE) VALUES ('POLICY_TM_ADD_EDIT_PROJECT_DESCRIPTION', 'Task', 0);

INSERT IGNORE INTO TM_POLICY (POLICY_ID, CATEGORY, POLICY_TYPE) VALUES ('POLICY_TM_MERGE_TERM_ENTRIES', 'Task', 0);

INSERT IGNORE INTO TM_ROLE_POLICY (ROLE_ID, POLICY_ID) SELECT ROLE_ID, 'POLICY_TM_ADD_EDIT_PROJECT_DESCRIPTION' FROM TM_ROLE_POLICY WHERE ROLE_ID IN ('super_user', 'power_user');

INSERT IGNORE INTO TM_ROLE_POLICY (ROLE_ID, POLICY_ID) SELECT ROLE_ID, 'POLICY_TM_MERGE_TERM_ENTRIES' FROM TM_ROLE_POLICY WHERE ROLE_ID IN ('super_user', 'power_user');

SET FOREIGN_KEY_CHECKS = 1;